// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Add/Delete Friends', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('Add/Delete Friends', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1052, height: 819 })
    await driver.findElement(By.css(".flex-row-reverse")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css(".text-grey")).click()
    vars["win4102"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win4102"])
    await driver.findElement(By.id("identifierId")).sendKeys("order2gathertest")
    await driver.findElement(By.id("identifierId")).sendKeys(Key.ENTER)
    await driver.wait(until.stalenessOf(await driver.findElement(By.id("identifierId"))), 30000)
    await driver.wait(until.elementIsEnabled(await driver.findElement(By.name("Passwd"))), 30000)
    await driver.findElement(By.name("Passwd")).sendKeys("order2gather~~")
    await driver.findElement(By.name("Passwd")).sendKeys(Key.ENTER)
    await driver.switchTo().window(vars["root"])
    await driver.wait(until.stalenessOf(await driver.findElement(By.css(".text-6xl"))), 30000)
    await driver.wait(until.elementLocated(By.css(".text-4xl")), 50000)
    await driver.findElement(By.xpath("//div[5]/a/button")).click()
    await driver.findElement(By.xpath("//a/button")).click()
    await driver.wait(until.elementLocated(By.css(".text-4xl")), 30000)
    {
      const element = await driver.findElement(By.xpath("//div[2]/button"))
      await driver.actions({ bridge: true }).move(element).perform()
    }
    {
      const element = await driver.findElement(By.css("body"))
      await driver.actions({ bridge: true }).move(element, 0, 0).perform()
    }
    await driver.findElement(By.xpath('//*[@id="root"]/div[2]/button')).click()
    {
      const element = await driver.findElement(By.xpath('//*[@id="root"]/div[2]/button'))
      await driver.actions({ bridge: true }).move(element).perform()
    }
    {
      const element = await driver.findElement(By.css("body"))
      await driver.actions({ bridge: true }).move(element, 0, 0).perform()
    }
    await driver.findElement(By.xpath("//input")).click()
    await driver.findElement(By.xpath("//input")).sendKeys("s0975247623@gmail.com")
    await driver.findElement(By.xpath("//input[2]")).click()
    await driver.findElement(By.xpath("//input[2]")).sendKeys("Weber")
    await driver.findElement(By.xpath("//div[5]/div/div/div/button[2]")).click()
    await driver.wait(until.elementLocated(By.css(".grid-cols-5 > .text-xl")), 30000)
    assert(await driver.findElement(By.css(".grid-cols-5 > .text-xl")).getText() == "Weber")
    await driver.findElement(By.css(".accent-blue")).click()
    await driver.findElement(By.css(".bg-red")).click()
  })
})