// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Create Restaurant', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('Create Restaurant', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1052, height: 819 })
    await driver.findElement(By.css(".flex-row-reverse")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css(".text-grey")).click()
    vars["win4102"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win4102"])
    await driver.findElement(By.id("identifierId")).sendKeys("order2gathertest")
    await driver.findElement(By.id("identifierId")).sendKeys(Key.ENTER)
    await driver.wait(until.stalenessOf(await driver.findElement(By.id("identifierId"))), 30000)
    await driver.wait(until.elementIsEnabled(await driver.findElement(By.name("Passwd"))), 30000)
    await driver.findElement(By.name("Passwd")).sendKeys("order2gather~~")
    await driver.findElement(By.name("Passwd")).sendKeys(Key.ENTER)
    await driver.switchTo().window(vars["root"])
    await driver.wait(until.stalenessOf(await driver.findElement(By.css(".text-6xl"))), 30000)
    await driver.wait(until.elementLocated(By.css(".text-4xl")), 50000)
    await driver.findElement(By.css(".flex:nth-child(5) .bg-blue")).click()
    {
      const element = await driver.findElement(By.css(".rounded-full"))
      await driver.actions({ bridge: true }).move(element).perform()
    }
    {
      const element = await driver.findElement(By.css("body"))
      await driver.actions({ bridge: true }).move(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".fa-plus")).click()
    {
      const element = await driver.findElement(By.css(".fa-plus"))
      await driver.actions({ bridge: true }).move(element).perform()
    }
    {
      const element = await driver.findElement(By.css("body"))
      await driver.actions({ bridge: true }).move(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".border-b:nth-child(1) .form_form_input__\\+cWOH")).click()
    await driver.findElement(By.css(".border-b:nth-child(1) .form_form_input__\\+cWOH")).sendKeys("Yummy")
    await driver.findElement(By.css(".border-b:nth-child(2) .form_form_input__\\+cWOH")).click()
    await driver.findElement(By.css(".border-b:nth-child(2) .form_form_input__\\+cWOH")).sendKeys("somewhere")
    await driver.findElement(By.css(".border-b:nth-child(3) .form_form_input__\\+cWOH")).click()
    await driver.findElement(By.css(".border-b:nth-child(3) .form_form_input__\\+cWOH")).sendKeys("0912345678")
    await driver.findElement(By.css(".hover\\3A bg-green")).click()
    await driver.findElement(By.css(".fa-xmark")).click()
    await driver.findElement(By.css(".fa-house > path")).click()
    await driver.wait(until.elementLocated(By.css(".flex:nth-child(5) .bg-blue")), 30000)
    await driver.findElement(By.css(".flex:nth-child(5) .bg-blue")).click()
    await driver.findElement(By.css(".w-44")).click()
    assert(await driver.findElement(By.css(".text-3xl")).getText() == "Yummy")
    await driver.findElement(By.css(".bg-red")).click()
    {
      const element = await driver.findElement(By.css(".bg-red"))
      await driver.actions({ bridge: true }).move(element).perform()
    }
    {
      const element = await driver.findElement(By.css("body"))
      await driver.actions({ bridge: true }).move(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".swal2-confirm")).click()
    {
      const element = await driver.findElement(By.css(".swal2-confirm"))
      await driver.actions({ bridge: true }).move(element).perform()
    }
    await driver.findElement(By.css(".swal2-confirm")).click()
  })
})