// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('Login', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1058, height: 822 })
    // for other e2e test cases
    // copy the code segment below and recode actions after login in Selenium IDE
    // ================================================================================
    await driver.findElement(By.css(".flex-row-reverse")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    await driver.findElement(By.css(".text-grey")).click()
    vars["win4102"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.switchTo().window(vars["win4102"])
    await driver.findElement(By.id("identifierId")).sendKeys("order2gathertest")
    await driver.findElement(By.id("identifierId")).sendKeys(Key.ENTER)
    await driver.wait(until.stalenessOf(await driver.findElement(By.id("identifierId"))), 30000)
    await driver.wait(until.elementIsEnabled(await driver.findElement(By.name("Passwd"))), 30000)
    await driver.findElement(By.name("Passwd")).sendKeys("order2gather~~")
    await driver.findElement(By.name("Passwd")).sendKeys(Key.ENTER)
    await driver.switchTo().window(vars["root"])
    await driver.wait(until.stalenessOf(await driver.findElement(By.css(".text-6xl"))), 30000)
    await driver.wait(until.elementLocated(By.css(".text-4xl")), 50000)
    // ====================================================================================================
    assert(await driver.findElement(By.css(".text-4xl")).getText() == "Order 2Gather")
  })
})
